---
- name: Deploy Nginx and Application
  hosts: all
  become: true
  gather_facts: no
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    app_repo: https://github.com/sayedrasmy/tmdb-devops-challenge/tmdb-devops-challenge.git

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Docker
      block:
        - name: Install dependencies
          package:
            name: "{{ item }}"
            state: present
          with_items:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg
            - lsb-release

        - name: Add Docker GPG apt key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker APT repository
          apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
            state: present

        - name: Install Docker
          package:
            name: docker-ce
            state: present

    - name: Clone application repository
      git:
        repo: "{{ app_repo }}"
        dest: /opt/app

    - name: Run Nginx container
      docker_container:
        name: nginx
        image: nginx
        ports:
          - "80:80"
        restart_policy: always
        state: started
        
