---
- name: Deploy Nginx and Application on AWS EC2
  hosts: nginx
  become: yes
  vars:
    repo_url: https://github.com/sayedrasmy/tmdb-devops-challenge
    app_dir: /var/www/app

  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - docker.io
        - git

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Clone repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: master

    - name: Create Nginx Dockerfile
      copy:
        content: |
          FROM nginx:latest
          COPY ./ /usr/share/nginx/html
        dest: "{{ app_dir }}/Dockerfile"

    - name: Build Nginx Docker image
      command: docker build -t tmdb-nginx:latest .
      args:
        chdir: "{{ app_dir }}"

    - name: Run Nginx container
      docker_container:
        name: tmdb-nginx
        image: tmdb-nginx:latest
        state: started
        ports:
          - "80:80"
