- name: Deploy Docker container to EC2
  hosts: nginx
  become: true
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == 'Debian'

    - name: Ensure Docker is started
      service:
        name: docker
        state: started

    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image_name }}"
        source: local

    - name: Run Docker container
      docker_container:
        name: my-nginx
        image: "{{ docker_image_name }}"
        state: started
        ports:
          - "80:80"
