---
- name: Deploy Nginx/IIS container
  hosts: nginx
  tasks:
    - name: Pull Nginx/IIS Docker image
      docker_image:
        name: nginx  # or the image name for IIS
        state: present

    - name: Run Nginx/IIS container
      docker_container:
        name: my-nginx  # or any suitable name
        image: nginx  # or the image name for IIS
        ports:
          - "80:80"
    - name: Deploy Application
  hosts: nginx
  tasks:
    - name: Clone application repository
      git:
        repo: https://github.com/sayedrasmy/tmdb-devops-challenge.git
        dest: /var/www/app

    - name: Build application
      command: npm install
      args:
        chdir: /var/www/app

    - name: Run application
      command: npm start
      args:
        chdir: /var/www/app
