--
- hosts: nginx
  become: true

  tasks:
    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Get the current working directory on the controller
      command: pwd
      register: pwd_output
      delegate_to: localhost

    - name: Set the current working directory as a fact
      set_fact:
        src_local: "{{ pwd_output.stdout }}"

    - name: Copy files to the destination on the remote server
      copy:
        src: "{{ src_local }}/"  # Ensure trailing slash to copy contents of the directory
        dest: /var/www/app/
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Build Docker image
      command: docker build -t myapp:latest {{ src_local }}/  # Assuming Dockerfile is in src_local
      args:
        chdir: /var/www/app/  # Ensure Docker build context is correct
  
    - name: Run image 
      command: docker run -p 3000 myapp:latest

    - name: Run Nginx container
      docker_container:
        name: nginx
        image: nginx:latest
        state: started
        ports:
          - "80:80"
        volumes:
          - /var/www/app/nginx.conf:/etc/nginx/conf.d/default.conf  # Adjust the path to your Nginx site configuration

  
  
  
