---
- hosts: web
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes
    - name: Copy application files
      command: pwd
      register: pwd_output
    
    - name: Set the current working directory as a fact
      set_fact:
        src_local: "{{ pwd_output.stdout }}"
    
    - name: Copy files to the destination
      copy:
        src: "{{ src_local }}"
        dest: /var/www/app/
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Build Docker image
      command: docker build -t myapp:latest /var/www/app
      command: docker run -p 3000 myapp:latest
    - name: Run Nginx container
      docker_container:
        name: nginx
        image: nginx:latest
        state: started
        ports:
          - "80:80"
        volumes:
          - /var/www/app/nginx.conf:/etc/nginx/conf.d/default.conf  # Adjust the path to your Nginx site configuration
        restart_policy: always
