- name: Deploy Docker container to EC2
  hosts: nginx
  become: true
  tasks:
    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image_name }}"
        source: local

    - name: Run Docker container
      docker_container:
        name: my-app
        image: "{{ docker_image_name }}"
        state: started
        ports:
          - "3000:3000"
    - name: Run Nginx Docker container
      docker_container:
        name: my-nginx
        image: nginx
        state: started
        restart_policy: always
        ports:
          - "80:80"
